// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpmeetEventBackend.Data;

#nullable disable

namespace UpmeetEventBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220621003509_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UpmeetEventBackend.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"), 1L, 1);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Details = "Concert",
                            Price = 200m,
                            Title = "Red Hot Chili Peppers"
                        },
                        new
                        {
                            EventId = 2,
                            Details = "Hockey Game",
                            Price = 50m,
                            Title = "Detroit Red Wings"
                        },
                        new
                        {
                            EventId = 3,
                            Details = "Baseball Game",
                            Price = 25m,
                            Title = "Detroit Tigers"
                        },
                        new
                        {
                            EventId = 4,
                            Details = "Basketball Game",
                            Price = 57m,
                            Title = "Detroit Pistons"
                        },
                        new
                        {
                            EventId = 5,
                            Details = "Concert",
                            Price = 89m,
                            Title = "Blink-182"
                        },
                        new
                        {
                            EventId = 6,
                            Details = "Craft Fair",
                            Price = 0m,
                            Title = "Ann Arbor Art fair"
                        });
                });

            modelBuilder.Entity("UpmeetEventBackend.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
